<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <AssemblyName>WebAppAngular</AssemblyName>
    <RootNamespace>WebAppAngular</RootNamespace>
    <SpaRoot>ClientApp\</SpaRoot>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Startup.cs" />
    <Compile Remove="Properties\AssemblyInfo.cs" />
  </ItemGroup>
</Project>
